# Generated by Django 5.1.4 on 2025-10-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0007_delete_filecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True, verbose_name='Está aprovado')),
                ('file', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/a/a3/Image-not-found.png', verbose_name='Arquivo')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='card.card', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'Arquivo do Card',
                'verbose_name_plural': 'Arquivos de Cards',
            },
        ),
    ]
