# Generated by Django 5.2.5 on 2025-09-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Está feito'),
        ),
    ]
