# Generated by Django 5.2.5 on 2025-09-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aprovação'),
        ),
        migrations.AddField(
            model_name='card',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de exclusão'),
        ),
    ]
