# Generated by Django 5.2.5 on 2025-09-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_approved_date_card_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.CreateModel(
            name='FileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, null=True, verbose_name='Está aprovado')),
                ('file', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/a/a3/Image-not-found.png', verbose_name='Arquivo')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='card.card', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'Arquivo do Card',
                'verbose_name_plural': 'Arquivos de Cards',
            },
        ),
    ]
