# Generated by Django 5.2.5 on 2025-09-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_remove_card_image_filecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card', verbose_name='Card'),
        ),
    ]
