# Generated by Django 5.1.4 on 2025-10-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_filecard_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileCard',
        ),
    ]
